version: '3.9'

services:
  freeswitch:
    image: deker1176/freeswitch:latest
    container_name: freeswitch
    restart: unless-stopped
    volumes:
      - ./freeswitch/conf:/usr/local/freeswitch/conf
    ports:
      - "8021:8021/tcp"
      - "16384-16590:16384-16590/udp"
    networks:
      sip_net:
        ipv4_address: 172.28.0.20

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasd
    ports:
      - "5432:5432"
    networks:
      sip_net:
        ipv4_address: 172.28.0.30

  kamailio:
    image: ghcr.io/kamailio/kamailio:5.8.3-bionic
    container_name: kamailio
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:5050/udp"
      - "5050:5050/tcp"
    volumes:
      - ./kamailio/config:/etc/kamailio
      - ./kamailio/logs:/var/log/kamailio
      - ./kamailio/postgres:/usr/share/kamailio/postgres/
    networks:
      sip_net:
        ipv4_address: 172.28.0.40

  rtpengine:
    container_name: rtpengine
    image: fonoster/rtpengine:latest
    build:
      context: .
    ports:
    - "2223:2223/udp"
    - "10000-10060:10000-10060/udp"
    #volumes:
    #  - ./mel_rtpengine/rtpengine.conf:/opt/rtpengine/rtpengine.conf
    environment:
      RTPENGINE_PUBLIC_IP: 202.181.148.92
      RTPENGINE_PORT_MIN: 10000
      RTPENGINE_PORT_MAX: 10060
      RTPENGINE_LOG_LEVEL: '6'
      RTPENGINE_BIND_NG_PORT: 2223
      port-min: 30000
      port-max: 30060
    networks:
      sip_net:
        ipv4_address: 172.28.0.50 


networks:
  sip_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16
